### ISSUE TITLE
Specify clear color value

### ISSUE THREAD

**Issue by sayan1an** [gboisse/gfx#39]
Could you please overload `gfxClearTexture/BackBuffer` with user specified color value.

**Comment by gboisse** [comment]
So the reason there isn't a clear color parameter is because you actually have to supply the clear color upon creating the texture object in D3D12 and then always clear to that same color value (or you'll get some validation warnings).

You can write your own compute shader though to clear to whatever color you want, is that an ok workaround for you?

**Comment by sayan1an** [comment]
Providing a pre-determined clear value should also work. However, `gfxCreateTexture2D` doesn't seem to have an overload that takes a clear-values.  I have several render targets with different clear-value for each.

**Comment by gboisse** [comment]
Hi, this should be fixed with https://github.com/gboisse/gfx/pull/78.

**Comment by gboisse** [comment]
Closing as fixed.
